"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-10-01 09:52:18.899106
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_name', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('channel_url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_identifier', sa.String(length=300), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=True),
    sa.Column('platform_id', sa.String(length=100), nullable=True),
    sa.Column('platform_display_name', sa.String(length=300), nullable=True),
    sa.Column('account_access', sa.String(length=40), nullable=True),
    sa.Column('followers_count', sa.BigInteger(), nullable=True),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('average_views', sa.Float(), nullable=True),
    sa.Column('average_views_sample_count', sa.Integer(), nullable=True),
    sa.Column('median_views', sa.Float(), nullable=True),
    sa.Column('top_video_title', sa.String(length=500), nullable=True),
    sa.Column('top_video_url', sa.String(length=2048), nullable=True),
    sa.Column('top_video_views', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('engagement_rate_basis', sa.String(length=20), nullable=True),
    sa.Column('engagement_sample_count', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('sub_genre', sa.String(length=80), nullable=True),
    sa.Column('genre_needs_review', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('secondary_language', sa.String(length=40), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('genre_confidence', sa.Float(), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('evidence_topics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('content_sample', sa.JSON(), nullable=True),
    sa.Column('data_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'normalized_identifier', name='uq_creator_identity')
    )
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creators_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_creators_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_creators_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_creators_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('ix_creators_status'), ['status'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('partial_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tracking_creators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_name', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('channel_url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_identifier', sa.String(length=300), nullable=False),
    sa.Column('identifier_type', sa.String(length=20), nullable=True),
    sa.Column('platform_channel_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('platform_name', sa.String(length=300), nullable=True),
    sa.Column('uploads_playlist_id', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('tracking_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_discovery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('videos_discovered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'normalized_identifier', name='uq_vt_creator_identity')
    )
    with op.batch_alter_table('video_tracking_creators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_tracking_creators_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_tracking_creators_platform_channel_id'), ['platform_channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_tracking_creators_username'), ['username'], unique=False)

    op.create_table('video_tracking_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_tracking_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_tracking_jobs_job_type'), ['job_type'], unique=False)

    op.create_table('video_tracking_uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('already_tracked', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.String(length=32), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'creator_id', name='uq_upload_creator')
    )
    with op.batch_alter_table('upload_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_items_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_items_upload_id'), ['upload_id'], unique=False)

    op.create_table('video_tracking_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('video_identifier', sa.String(length=100), nullable=False),
    sa.Column('video_url', sa.String(length=2048), nullable=False),
    sa.Column('creator_name', sa.String(length=300), nullable=True),
    sa.Column('owner_username', sa.String(length=100), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_views', sa.BigInteger(), nullable=True),
    sa.Column('previous_views', sa.BigInteger(), nullable=True),
    sa.Column('views_gained', sa.BigInteger(), nullable=True),
    sa.Column('growth_pct', sa.Float(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('engagement_basis', sa.String(length=20), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['video_tracking_creators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['video_tracking_uploads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'video_identifier', name='uq_vt_video_identity')
    )
    with op.batch_alter_table('video_tracking_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_tracking_videos_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_tracking_videos_creator_name'), ['creator_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_tracking_videos_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_tracking_videos_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_tracking_videos_status'), ['status'], unique=False)

    op.create_table('video_tracking_sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_chars', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video_tracking_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_tracking_sentiment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_tracking_sentiment_video_id'), ['video_id'], unique=False)

    op.create_table('video_tracking_view_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_tracking_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_tracking_view_history', schema=None) as batch_op:
        batch_op.create_index('ix_vt_history_video_time', ['video_id', 'captured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_tracking_view_history', schema=None) as batch_op:
        batch_op.drop_index('ix_vt_history_video_time')

    op.drop_table('video_tracking_view_history')
    with op.batch_alter_table('video_tracking_sentiment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_tracking_sentiment_video_id'))

    op.drop_table('video_tracking_sentiment')
    with op.batch_alter_table('video_tracking_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_tracking_videos_status'))
        batch_op.drop_index(batch_op.f('ix_video_tracking_videos_sentiment'))
        batch_op.drop_index(batch_op.f('ix_video_tracking_videos_platform'))
        batch_op.drop_index(batch_op.f('ix_video_tracking_videos_creator_name'))
        batch_op.drop_index(batch_op.f('ix_video_tracking_videos_creator_id'))

    op.drop_table('video_tracking_videos')
    with op.batch_alter_table('upload_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_items_upload_id'))
        batch_op.drop_index(batch_op.f('ix_upload_items_creator_id'))

    op.drop_table('upload_items')
    op.drop_table('video_tracking_uploads')
    with op.batch_alter_table('video_tracking_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_tracking_jobs_job_type'))

    op.drop_table('video_tracking_jobs')
    with op.batch_alter_table('video_tracking_creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_tracking_creators_username'))
        batch_op.drop_index(batch_op.f('ix_video_tracking_creators_platform_channel_id'))
        batch_op.drop_index(batch_op.f('ix_video_tracking_creators_platform'))

    op.drop_table('video_tracking_creators')
    op.drop_table('uploads')
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creators_status'))
        batch_op.drop_index(batch_op.f('ix_creators_sentiment'))
        batch_op.drop_index(batch_op.f('ix_creators_platform'))
        batch_op.drop_index(batch_op.f('ix_creators_language'))
        batch_op.drop_index(batch_op.f('ix_creators_genre'))

    op.drop_table('creators')
    # ### end Alembic commands ###
