"""video tracking job locks

Revision ID: 0003_job_locks
Revises: 0002_upload_rows
Create Date: 2026-10-01 09:56:53.351773
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003_job_locks'
down_revision: str | None = '0002_upload_rows'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_tracking_job_locks',
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_tracking_job_locks')
    # ### end Alembic commands ###
