"""api usage

Revision ID: 0004_api_usage
Revises: 0003_job_locks
Create Date: 2026-10-01 10:18:11.479502
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004_api_usage'
down_revision: str | None = '0003_job_locks'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=30), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=16), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('quota_exceeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('day', 'service', 'key_fingerprint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage')
    # ### end Alembic commands ###
