"""api rate status

Revision ID: 0005_api_rate_status
Revises: 0004_api_usage
Create Date: 2026-10-01 10:33:13.635751
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005_api_rate_status'
down_revision: str | None = '0004_api_usage'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_status',
    sa.Column('service', sa.String(length=30), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('regain_access_minutes', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_rate_status')
    # ### end Alembic commands ###
