"""Add profile_picture_url

Revision ID: d1eb377704e1
Revises: 0005_api_rate_status
Create Date: 2026-10-07 09:45:48.482467
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd1eb377704e1'
down_revision: str | None = '0005_api_rate_status'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('profile_picture_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creators', 'profile_picture_url')
    # ### end Alembic commands ###
